class NonverbalClock {
  constructor() {}
  drawClock() {
    //------------------strt---------------
    Graphics.prototype.setFontNonVerbal = function (scale) {
      // Actual height 59 (63 - 5)
      this.setFontCustom(
        atob(
          "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAB4AAAAAAAAAAAA/AAAAAAAAAAAAf4AAAAAAAAAAAP/AAAAAAAAAAAH/4AAAAAAAAAAB/8AAAAAAAAAAAP/AAAAAAAAAAAB/gAAAAAAAAAAAPwAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAAAAAAAAHwAAAAAAAAAAAH8AAAAAAAAAAAP/AAAAAAAAAAAf/gAAAAAAAAAA//gAAAAAAAAAA//AAAAAAAAAAB/+AAAAAAAAAAD/8AAAAAAAAAAH/8AAAAAAAAAAH/4AAAAAAAAAAP/wAAAAAAAAAAf/wAAAAAAAAAA//gAAAAAAAAAA//AAAAAAAAAAB/+AAAAAAAAAAD/+AAAAAAAAAAH/8AAAAAAAAAAH/4AAAAAAAAAAP/wAAAAAAAAAAf/wAAAAAAAAAAP/gAAAAAAAAAAAAAAAAAAHAAAAAAAAAAAP/4AAAAAAAAAH///AAAAAAAAB///44AAAAAAAf//wAOAAAAAAH//8AABwAAAAAB//wAAAcAAAAAA//AAAOHgAAAAAP+AAADj4AAAAAH+AAAA/+AAAAAD/AAAAP/gAAAAB/gAAAH/4AAAAA/gAAAB/+AAAAAPwAAAA//AAAAAH4AgAAf/gAAAAD8AMAAf/4AAAAB/DH////4AAAAA/h/////gAAAAAd6/////AAAAAAPc//APzwAAAAAD3P93gA4AAAAAA9z4P4AcAAAAAAPc4B+AOAAAAAAD7OAfAPAAAAAAA+3wD4HgAAAAAAH+8B/jwAAAAAAB9jg//4AAAAAAAP8cef8AAAAAAAB/jPB+AAAAAAAAP8/4HAAAAAAAAD///DgAAAAAAAAP/w7wAAAAAAAAB/8H4AAAAAAAAAH+B8AAAAAAAAAAfB+AAAAAAAAAADj/AAAAAAAAAAA//AAAAAAAAAAAH+AAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAAAAB/8AAAAAAAAAAA//4AAAAAAAAAAf//gAAAAAAAAAP+D+AAAAAAAAADngH/gAAAAAAADw8AP+AAAAAAAD+HgB/wAAAAAAA/x8AP+AAAAAAAcf3AD/gAAAAAAGB/wA44AAAAAABgH8AcGAAAAAAA+Bv8HxgAAAAAAf+f/z/4AAAB/AOf////+AAAAf//P//H//gAAAMP/3//gf/4AAADgz/9/wDwMAAAAcIb7P8AcDAAAAD+GPw/gH/gAAAAf9h8H8B/4AAAAA/+eEfA/8AAAAAB//zgwfAAAAAAAB//4EfAAAAAAAAAf/A/AAAAAAAAAAH//AAAAAAAAAAAf/AAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH8AAAAAAAAAAAH/8AAAAAAAAAAD//4AAAAAAAAAB7x/gAAAAAAAAD8cB+AAAAAAAAD+HwD/4AAAAAAA/w8Af+AAAB/wAP/bgD/wAAAf/8D/+8A4MAAAH///7f/gODAAABgb//z/4DgwAAAcGM/87/w4MAAAHhjB+H//f/AAAA/4gbA////wAAAD/8GbP8P/8AAAAH//nx8A9/AAAAAD/58PgPAwAAAAAB+eD8BwMAAAAAADDw/AcDAAAAAADwuAAHBwAAAAAH+JwAB/4AAAAA/9meAA/+AAAAP/4ZnyAf/gAAAD/GHBf///wAAABwwg////gAAAAAYMP////wAAAAAGD/////AAAAAAB///wAAAAAAAAAP/8AAAAAAAAAAA+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAAAAAAAAAB/4AAAAAAAPgAA//gAAAAAAD/AA/d/AAAAAAAx+Afjh/AAAAAAOH4GecH/AAAAAB7vjD3A/4AAAAAPw/4fYGOAAAAAA+d/j/BgwAAAAAD+H+fw4MAAAAAAPz/////AAAAAAA//P///wAAAAAAB/n///8AAAAAAAGx/w//AAAAAAAHgf8HAwAAAAA3/wPABw8AAAAA//8GwAf/AAAAAf+xhoAH/gAAAAGGIYzAB/4AAAAB5j//8A/8AAAAAP////geAAAAAAB////8eAAAAAAAAAAPcfAAAAAAAAAADgfAAAAAAAAAABwfgAAAAAAAAAA8fgAAAAAAAAAAffgAAAAAAAAAAMPgAAAAAAAAAADPgAAAAAAAAAABngAAAAAAAAAAAbwAAAAAAAAAAAG4AAAAAAAAAAAB8AAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAA/AAAAAAAAAAAAP8AAAAAAAAAAAGPwAAAAAAAAAAAx+AAAAAAAAAAAPb4AAAAAAAAAAB8/gAAAAAAAAAAH9+AAAAAAAAAAA/P+AAAAAAAAAADz/+AAAAAAAH8Afz/+AAAAAAD//h8d/wAAAAAAz//+GA/AAAAAAMH//DgB84AAAADhjHwwAP/AAAAA/4x/MMB/4AAAAD/8f/HAP+AAAAAH//vz8DhgAAAD7//85/AwcAAAB////G////AAAAf///h////wAAAEGGHaf9//8AAABhhgzzwD//AAAAf+Z88cAf/wAAAH///PHAHMMAAAAf//xw4A4DAAAAAA/8cOAOBgAAAAAAHDgAD44AAAAAAfwcAA/+AAAAAH/8HgAf/AAAAAf/zB9AP/wAAAAP/M4Xw//4AAAADzDH///4AAAAABww////wAAAAAAMH////gAAAAAAD//8AAAAAAAAAAf/gAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAAAAAAAAAAPAAAAAAAAAAAAH4AAAAAAAAAAABngAAAAAAAAAAAM8AAAAAAAAAAAB/gAAAAAAAAAAAP8AAAAAAAAAAAB/gAAAAAAAAAAAOfAAAAAAAAAGAB/+AAAAAAAAD/gPP8AAAAAAAB//zBv4AAAAAAAcf/wgPvAAAAAAD+P4YA/4AAAAAAP/OGAD/AAAAAAAf/BGAfwAAAAAP//wTgGEAAAAAH//4BgDhgAAAABjH+AQA44AAAAAexhgAfueAAAAAH//4Ef//gAAAAA//+BPD/4AAAAAAH/gDAcMAAAAAAAH4BgH/AAAAAAC/+AAB/wAAAAAD/5wcAf4AAAAAB/Gf/gP+AAAAAAc////DgAAAAAAD//8fxwAAAAAAA/8AD84AAAAAAAAAABzcAAAAAAAAAAAceAAAAAAAAAAAPvAAAAAAAAAAAGfgAAAAAAAAAADDgAAAAAAAAAAAxwAAAAAAAAAAAZ4AAAAAAAAAAAGYAAAAAAAAAAAA8AAAAAAAAAAAAPAAAAAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB/gB/gAAAAAAAAf/g//wAAAAAAAMP////gAAAAAABw/+fP/AAAAAAAf8ft7P+AAAAAAB/mf/wP4AAAAAAH/j/4cf/AAAADgP//+OB/4AAAB////v/AP+AAAAf///f/gBxwAAAMD//n7/wccAAADgxhxwf/PDAAAAf8YMf/z//wAAAD///H+/H/8AAAAD//x/Pw//AAAAAB/8Th8HzwAAAAAAPB4IBwMAAAAAP/yfAAcPAAAAD//8n4AH/gAAAB//jL/AD/4AAAAYYY45+B/8AAAAGGH//////AAAAB///////AAAAAAP/////+AAAAAAA//gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAD8AAAAAAAAAAAA/wAAAAAAAAAAAM+AAAAAAAAAAADnwAAAAAAAAAAAfvAAAAAAAAAAAD78AAAAAAAAAAAP34AAAAAAAAAAB4/wAAAAAAAAAA///wAAAAAAAAAf/H/wAAAAAAAAGfAD/AAAAAAAABvwwD+AAAAAAAAbcMAH/gAAAAAAHvmGA/8AAAAf+A//jkH/gAAAP////x/A4YAAADB/////4OGAAAAwYR/n9/jhgAAAPGAG/u///4AAAB/wBn5+D++AAAAH//48fAP/gAAAAH/+Of4D+4AAAAAAfh3/AcGAAAAAAf4PwwHBgAAAAH/+D8ABw4AAAAf/zgfAA/8AAAAP+YYJ5Af/AAAADDjH/////gAAAA+//////jgAAAAH//////AAAAAAAf/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAAA+AAAAAAAAAAAAPwAAAAAAAAAAADOAAAAAAAAAAAA5wAAAAAAAAAAAH+AAAAAAAAAAAA84AAAAAAAAAAAHfAAAAAAAAAB+A+8AAAAAAAAAf8HPwAAAAAAAAMP47/AAAAAAAADg//z+AAAAAAAAeM/wH8AAAAAAAD+P4Af4AAAAAAAP3GAD/gAAAAAAA/jAAx+AAAAAAAD/wAAH/wAAAAAAf+AAwf+AAAAAAP//AMH/gAAAAADG/wABwcAAAAAAxv+D8YHAAAAAAMfPj/+AwAAAAAB//f//gcAAAAAAf/j4D8PAAAAAAB/w+AfAwAAAA//+cHwHAYAAAB///Df8BwGAAAAf/4w/zAcDgAAAMGMMHwAH/wAAADxjjB8AB/8AAAAf/7+fgB/+AAAAD////////gAAAAH/////+PwAAAAAAAAB/+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAfgAAAAAAAAAAAGeAAAAAAAAAAABzwAAAAAAAAAAAO+AAAAAAAAAAAB/wAAAAAAAAAAAPOAAAAAAAAAHAB/wAAAAAAAAD+APPAAAAAAAAA/8Bx+AAAAAAAAMP4P/8AAAAAAADh/x8f4AAAAAAA/w/uH/gAAAAAAD+P/BB/AAAAAAAP7HgAD/+AAAAHwfxwYAP/wAAAB/x/4GAA/8AAAAx//+BgAHDgAAAMH//AQABwYAAABxh/wMQAf+AAAAf4Y8DEGH/wAAAB/mDAhP5/8AAAAH/xwYP+//AAAAAP/8GXgv/wAAAAAH//vgDn8AAAAAAH/+wA4HAAAAAAD//+AOBgAAAAAB9/f4D/4AAAAAAZvx+A/+AAAAAAGb8PAP/AAAAAAAn/MAH/gAAAAAAP/3AHwAAAAAAAB//w/wAAAAAAAAP///wAAAAAAAAAAP/wAAAAAAAAAAADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAACAAAAAAAAPAAAB4AAAAAAAH4AAA/AAAAAAAD/AAAf4AAAAAAB/4AAP/AAAAAAA/+AAH/4AAAAAAP/gAB/8AAAAAAB/4AAP/AAAAAAAP8AAB/gAAAAAAB+AAAPwAAAAAAAOAAAB4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=="
        ),
        46,
        atob("FhYoKCgoKCgoKCgoFg=="),
        80 + (scale << 8) + (1 << 16)
      );
      return this;
    };
    // timeout used to update every minute
    let drawTimeout;

    // schedule a draw for the next minute
    function queueDraw() {
      if (drawTimeout) clearTimeout(drawTimeout);
      drawTimeout = setTimeout(function () {
        drawTimeout = undefined;
        draw();
      }, 60000 - (Date.now() % 60000));
    }

    function draw() {
      let x = g.getWidth() / 2;
      let y = g.getHeight() / 2;
      g.reset();
      // work out locale-friendly date/time
      let date = new Date();
      let timeStr = require("locale").time(date, 1);
      let dateStr = require("locale").date(date);
      // draw time
      g.setFontAlign(0, 0).setFont("NonVerbal");
      g.clearRect(0, y - 40, g.getWidth(), y + 40); // clear the background
      g.drawString(timeStr, x, y);
      // draw date
      y += 35;
      //g.setFontAlign(0,0).setFont("4x6"); "Vector", 20
      g.setFontAlign(0, 0).setFont("Vector", 15);
      //g.clearRect(0,y-4,g.getWidth(),y+4); // clear the background
      //g.drawString(dateStr,x,y);
      // queue draw in one minute
      queueDraw();
    }

    // Clear the screen once, at startup
    g.clear();
    // draw immediately at first, queue update
    draw();
    // Stop updates when LCD is off, restart when on
    Bangle.on("lcdPower", (on) => {
      if (on) {
        draw(); // draw immediately, queue redraw
      } else {
        // stop draw timer
        if (drawTimeout) clearTimeout(drawTimeout);
        drawTimeout = undefined;
      }
    });
    // Show launcher when middle button pressed
    Bangle.setUI("clock");
    // Load widgets
    Bangle.loadWidgets();
    Bangle.drawWidgets();
    //======================end==========
  }
  onInit() {
    g.clear();
    this.drawClock();
  }
}

new NonverbalClock().onInit();
